

export enum COLOURS {
  MAIN_PAGE_YELLOW = "#ffec4b",
  MAIN_PAGE_BLACK = "black",
  MAIN_PAGE_WHITE = "white",
  BACKGROUND_COLOR = '#f2f2f2',
  LOGIN_BACKGROUND = '#f6de56',
  ADMIN_PAGE_BUTTON_COLOR = '#ff1a4c',
  BUTTON_LETTER_COLOR = 'white',
  ORDER_PLACE_COLOR = '#d34412',
  TABLE_BUTTON_HOVER_COLOR = '#f67122',
  CANCEL_COLOR='red',
  OK_COLOUR = '#5cf852',
  HOVER_BUTTON_COLOR = '#d9d9d9',
  VIP_COLOR = '#dd0939',
  MAIN_PAGE_BUTTON_COLOR_YELLOW = '#dd5e09',

}

export enum SIZES {
  MAIN_PAGE_BUTTON_BORDER_RADIOUS = 20,
  TABLE_BUTTON_WIDTH = '18vw',
  TABLE_BUTTON_HEIGHT = '15vh',
  LOGIN_FORM_INPUT_WIDTH = '20vw',
  FORM_FIELD_MARGIN = 5,
  ADMIN_PAGE_BUTTON_WIDTH = '180px',
  USER_PAGE_PAGINATION_SIZE = 7,
  CATEGORY_ITEM_HEIGHT = '100px',
  ORDER_PAGE_SIZE = 10,
}


export enum REQUEST {
  POST = 'POST',
  PUT = 'PUT',
  DELETE = 'DELETE',
  UPDATE = 'UPDATE'
}
